borg-backup.nix: exclude /etc/nix/nix.conf
Restoring the backup to /mnt so that /mnt/etc/nix/nix.conf exists at
the time of `nixos-install` does not work:

  $ nixos-install
  copying Nix to /mnt....
  ...
  error: opening file '/etc/nix/nix.conf': No such file or directory

This is due to nix.conf being a symlink to (a symlink to) the Nix store, which
is not backed up (because I rely on NixOS live CD/USB).